### ISSUE TITLE
Another auth error

### ISSUE THREAD

**Issue by kerri-hicks** [jfaustin/Tweet-gater#8]
Hi! So the install process went fine until I got to the final auth step. Checked to make sure iconv was enabled (it is), and we're running PHP 5.3.3. 

twitter_oauth.php throws a server error (I don't have access to the console, so I can't check the logs, sadly). So I installed Tweetgater on another server, and at the same point, I get this:

Fatal error: Uncaught exception 'Zend_Oauth_Exception' with message 'Could not retrieve a valid Token response from Token URL: Failed to validate oauth signature and token' in /tweetgater/inc/Zend/Oauth/Http.php:234 Stack trace: #0 /tweetgater/inc/Zend/Oauth/Http.php(190): Zend_Oauth_Http->_assessRequestAttempt(Object(Zend_Http_Response)) #1 /tweetgater/inc/Zend/Oauth/Http.php(191): Zend_Oauth_Http->startRequestCycle(Array) #2 /tweetgater/inc/Zend/Oauth/Http.php(191): Zend_Oauth_Http->startRequestCycle(Array) #3 /tweetgater/inc/Zend/Oauth/Http/RequestToken.php(51): Zend_Oauth_Http->startRequestCycle(Array) #4 /tweetgater/inc/Zend/Oauth/Consumer.php(115): Zend_Oauth_Http_RequestToken->execute() #5 /tweetgater/install/twitter_oauth.php(20): Z in /tweetgater/inc/Zend/Oauth/Http.php on line 234

Any ideas? Should I update to the latest Zend, or will Tweetgater not work with it?

Thanks so much for this cool tool!

**Comment by jfaustin** [comment]
Hey Kerri,

I think the new version of Zend Framework will work.  Let me try some stuff in my test environment and get back to you.  I've tested on 5.3.2, but not on 5.3.3.  I may push out a new version that includes retweet support with it as well as checking this bug out.
- Jason

**Comment by kerri-hicks** [comment]
Terrific, thanks a million. I'll be on tenterhooks. ;-)
